### ISSUE TITLE
勾选不在本地保留备份后，获取不到非图片格式文件大小

### ISSUE THREAD

**Issue by Andowa** [sy-records/qiniu-kodo-wordpress#21]
您好，使用此插件：勾选不在本地保留备份，上传附件不显示文件大小(只是图片会显示大小，其他附件，比如：压缩包，视频文件，音频文件都不会显示大小)。
之前在阿里云OSS插件上反馈过：https://github.com/sy-records/aliyun-oss-wordpress/issues/32
应该是类似的问题，烦请大佬看看

**Comment by sy-records** [comment]
试试吧 #22

**Comment by Andowa** [comment]
> 试试吧 #22

嗯，可以正常显示了，感谢
