### ISSUE TITLE
操作删除文件时，会提示发生错误，且只会清理wordpress中的记录，不清理储存桶中的文件

### ISSUE THREAD

**Issue by Andowa** [sy-records/qiniu-kodo-wordpress#23]
文件删除是正常操作了，但仅限于wordpress记录中，对象存储桶中文件依旧存在。
![image](https://github.com/user-attachments/assets/663aaeb7-d3f4-4b54-94cf-cfdcf5b85731)

**Comment by sy-records** [comment]
修改`wp-config.php`，打开 `WP_DEBUG`，重新操作后查看`wp-content/debug.log`日志信息。

```php
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```

**Comment by Andowa** [comment]
> 修改`wp-config.php`，打开 `WP_DEBUG`，重新操作后查看`wp-content/debug.log`日志信息。
> 
> ```
> define('WP_DEBUG', true);
> define('WP_DEBUG_LOG', true);
> define('WP_DEBUG_DISPLAY', false);
> ```

开启并操作后，日志文件中没有相关的内容。
![image](https://github.com/user-attachments/assets/1b1935a7-952e-463d-8435-277af22573a0)

**Comment by sy-records** [comment]
那你自己调试下吧

```php
// 413行
var_dump($meta);

// 440行
var_dump($deleteObjects);
```

https://github.com/sy-records/qiniu-kodo-wordpress/blob/ce2a3cdd2808feac331b66b348b78ebe58bc570e/qiniu-kodo-wordpress.php#L413-L440

删除远程失败的话，会在这里写入日志

```php
// 171行
var_dump($_, $err);
```

https://github.com/sy-records/qiniu-kodo-wordpress/blob/ce2a3cdd2808feac331b66b348b78ebe58bc570e/qiniu-kodo-wordpress.php#L170-L173

**Comment by Andowa** [comment]
抱歉，是我自己的问题，有些插件和这个冲突了
