### ISSUE TITLE
在禁用`以年—月目录形式组织上传内容`后，缩略图路径中有`./`

### ISSUE THREAD

**Issue by rise0chen** [sy-records/qiniu-kodo-wordpress#4]
在禁用`以年—月目录形式组织上传内容`后，缩略图路径中有`./`

**Comment by sy-records** [comment]
缩略图格式是什么？
插件配置是什么？

**Comment by rise0chen** [comment]
![image](https://user-images.githubusercontent.com/12853908/159209382-b64b0d0a-5166-46e6-a29c-fefb44d19ad0.png)

**Comment by rise0chen** [comment]
![image](https://user-images.githubusercontent.com/12853908/159209426-e1dd6cef-2fb4-4340-98fe-b27a06fb08ac.png)

**Comment by sy-records** [comment]
你服务器是linux还是windows？
