### ISSUE TITLE
远程抓取图片功能无法起作用

### ISSUE THREAD

**Issue by Rockyzsu** [sy-records/qiniu-kodo-wordpress#6]
你好，目前使用的1.3.0 版本
正常插入图片，能够上传到七牛。

而在写文章时里面，选择抓取远程的图片时，却发现图片并没有被上传到七牛。有时候文件名也不会被正常显示

![](http://xximg.30daydo.com/sharex/20220425113656.png)

![](http://xximg.30daydo.com/sharex/20220425113756.png)

**Comment by sy-records** [comment]
仅支持从媒体库上传图片。

**Comment by Rockyzsu** [comment]
那个选项是多余的？

**Comment by sy-records** [comment]
那就是你用错插件，问错地方了。
