### ISSUE TITLE
能否增加定时备份（数据库）功能？

### ISSUE THREAD

**Issue by qglian** [sy-records/qiniu-kodo-wordpress#7]
这款软件非常好，还有一个就是希望能**定期自动备份数据库到七牛云**，用VPS的话宝塔有七牛云插件可以直接备份数据库，而虚拟主机就不行了，市场有一些但不完善，请加以考虑，如果觉得有必要的话，谢谢。

### 需求背景：

使用虚拟主机的话，希望能定期自动备份网站和（特别是）数据库到 七牛云，可以参考第二个插件的最下部分。

现在有几款可以借鉴：
**第一个： Backup Qiniu Lite** 
https://gitee.com/beizigen/wordpress-backup-qiniu-lite
这款插件优点是可以定期备份数据库，附件实时备份到七牛云；缺点是只是备份，不能像qiniu-kodo-wordpress这样直接存到七牛云并调用附件和图片。
![image](https://user-images.githubusercontent.com/65819267/175476077-bd92431d-fe91-4158-a17e-082a2f17e5a0.png)

**第二个：WP-QINIU （WordPress连接到七牛云存储）**
https://cn.wordpress.org/plugins/wp-qiniu/

这款插件优点是可以定期备份数据库和网站到七牛云；缺点是从七牛云调用附件现在报错了，作者很久没更新了，但是可以借鉴，如下图
![image](https://user-images.githubusercontent.com/65819267/175477538-a0bd7010-f10d-49b4-b15d-97affc712eeb.png)

**Comment by sy-records** [comment]
感谢你的反馈。

但是目前这个插件的作用只是用于媒体库的图片资源上传，暂不考虑添加备份功能。

这个应该寻找更合适的插件来处理。
